version: '3.9'
services:
  db:
    image: postgres:alpine
    volumes:
      - db_data:/var/lib/postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: compito
volumes:
  db_data:
    name: compito-db
