name: Deploy API
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.REMOTE_SERVER_ADDRESS }} >> ~/.ssh/known_hosts

      - uses: actions/checkout@v2
      - name: Build API
        run: |
          npm install
          npm run build api

      - name: Zip artifacts
        env:
          REMOTE_SERVER_USER: ${{ secrets.REMOTE_SERVER_USER }}
          REMOTE_SERVER_ADDRESS: ${{ secrets.REMOTE_SERVER_ADDRESS }}
        run: |
          zip build.zip package.json package-lock.json prisma/**/* dist/apps/api/**/*
          rsync -azIve ssh ./build.zip $REMOTE_SERVER_USER@$REMOTE_SERVER_ADDRESS:/home/$REMOTE_SERVER_USER/compito/build.zip
      - name: Deploy API to server
        uses: appleboy/ssh-action@master
        env:
          REMOTE_SERVER_USER: ${{ secrets.REMOTE_SERVER_USER }}
        with:
          host: ${{ secrets.REMOTE_SERVER_ADDRESS }}
          username: ${{ secrets.REMOTE_SERVER_USER }}
          password: ${{ secrets.REMOTE_SERVER_PASSWORD }}
          envs: REMOTE_SERVER_USER
          script: |
            cd /home/$REMOTE_SERVER_USER/compito
            unzip build.zip
            rm -rf build.zip
            npm install
            npm prisma migrate deploy
            pm2 stop compito
            pm2 start dist/apps/api/main.js --name compito
